name: Staging Docker Imaging - Sentiment Prediction

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - "main.py"
      - "preprocess.py"
      - "requirements.txt"

env:
  TAGS: ${{ github.sha }}
  
  # Please fill this
  DOCKER_REPOSITORY: kaenova/traveloka-sentiment-prediction

jobs: 
  DockerImagingService:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: "." # Don't forget to fill this
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build --tag "$DOCKER_REPOSITORY:$TAGS" --tag "$DOCKER_REPOSITORY:latest" .

      - name: DockerHub Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Dockerhub Push
        run: docker push $DOCKER_REPOSITORY --all-tags